### ISSUE TITLE
Para resolver aquele problema da tabela.

### ISSUE THREAD

**Issue by DouglasVarollo** [Tiaguin061/LauchBaseModulo4#2]
- Primeira forma

Lá no seu CSS você precisa adicionar a proprieade height no seletor .table-container tbody tr td:first-child
```css
.table-container tbody tr td:first-child {
    display: grid;
    grid-template-columns: 64px 1fr;
    align-items: center;
    height: -webkit-fill-available;
}
```
Você pode ver a compatibilidade do valor "fill-available" [aqui](https://caniuse.com/#search=fill-available).

- Segunda forma
```js
<script>
  const tbodyTds = document.querySelectorAll('tbody tr td:first-child');

  tbodyTds.forEach(td => {
    td.style.height = `${td.parentElement.offsetHeight}px`;
  })
</script>
```
Você precisa adicionar esse script lá no seu **instructors/index.njk** depois da div.
